server:
  port: 9292


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Mobiles?createDatabaseIfNotExist=true
    username: root
    password: mohan@123
    driver-class-name: com.mysql.cj.jdbc.Driver



jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: rg.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: none


